### ISSUE TITLE
Does not follow spec

### ISSUE THREAD

**Issue by eccles** [spdx/tools-golang#101]
Just used this for the first time and I note that this code has 2 string slices in CreatorInfo called CreatorPersons and CreatorOrganizations.

However the spec for 2.2.1 only has a scalar Creator field which is specified in the NTIA report.

The spec is here: https://spdx.github.io/spdx-spec/v2-draft/ - hopefully I have this right

and the NTIA report: https://www.ntia.doc.gov/files/ntia/publications/ntia_sbom_formats_energy_brief_2021.pdf

**Comment by swinslow** [comment]
Hi @eccles, thanks for reaching out on this.

My understanding of the 2.2.1 spec is that it is mandatory to have at least one Creator specified, but it is permitted to have more than one. See https://spdx.github.io/spdx-spec/v2-draft/document-creation-information/#68-creator-field -- Cardinality is specified as `1..*`

For the golang tools, if more than one Creator is stored in the CreationInfo for a Document, then when it is written to disk (via tvsaver) it should render each one on a separate line. The NTIA report on page 6 shows an example of this -- in that case it shows one Creator Person and one Creator Tool, but there could be more than one.

Let me know if you're seeing something different, or if I'm misunderstanding your issue!

**Comment by eccles** [comment]
yes - thanks for this - I see I am actually misreading the spec - my apologies for the noise and thank you for your considered response. 

I have been writing testcode for this and this made me realise what is actually happening.
Closing ticket.
