### ISSUE TITLE
builder: File paths are not relative

### ISSUE THREAD

**Issue by swinslow** [spdx/tools-golang#107]
From at least one test when running `idsearcher` and `builder` on a directory, the file paths for FileName are being generated incorrectly as `/filename.txt` rather than `./filename.txt`.

[The SPDX spec requires](https://spdx.github.io/spdx-spec/file-information/#81-file-name-field) that the FileName field consist of relative paths.

**Comment by CatalinStratu** [comment]
Hi, can I handle this issue?
I really want to participate in GSOC in this project and the more issues I solve, the better I will understand the project!

**Comment by swinslow** [comment]
@CatalinStratu sure! Thank you for the offer  :)

It looks like you've been getting familiar with the tools-golang codebase, but just to help point you in the right direction, here's where I think you're going to want to look:
* the [`builder/`](https://github.com/spdx/tools-golang/tree/main/builder) directory contains the code which scans a directory and creates an SPDX Document based on its contents
* I think the relevant code where the issue is coming from is going to be either in [build_file.go](https://github.com/spdx/tools-golang/blob/9eeb46e841a8558ac3bad1cde8b91b8f63b39219/builder/builder2v2/build_file.go#L18) and/or [build_package.go](https://github.com/spdx/tools-golang/blob/9eeb46e841a8558ac3bad1cde8b91b8f63b39219/builder/builder2v1/build_package.go#L17), or possibly b/c of a call to [utils.GetAllFilePaths](https://github.com/spdx/tools-golang/blob/9eeb46e841a8558ac3bad1cde8b91b8f63b39219/utils/filesystem.go#L20)
* Once you've sorted out the issue, note that it might require changes to both [builder2v1](https://github.com/spdx/tools-golang/tree/main/builder/builder2v1) and [builder2v2](https://github.com/spdx/tools-golang/tree/main/builder/builder2v2) in order to handle both SPDX-2.1 and SPDX-2.2 files correctly

Take a look and let me know if you run into any issues. Thanks again!

**Comment by swinslow** [comment]
Oh, and also to test this out, you can use [Example #3](https://github.com/spdx/tools-golang/blob/main/examples/3-build/example_build.go) as a command-line tool to call the builder functions.

Just run `go build` in that directory and then it should give you details on how to run it. You can then look at the SPDX Document it generates and check the `FileName` fields to see whether or not they are showing up with relative vs. absolute filepaths.

**Comment by CatalinStratu** [comment]
Hi, what do you think about "FileName:" from screenshot?
![image](https://user-images.githubusercontent.com/28156781/158138047-5e2da3a2-7b58-4d64-85db-990e1bec2761.png)

**Comment by swinslow** [comment]
Hi @CatalinStratu, take a look at my comment on your PR at https://github.com/spdx/tools-golang/pull/114#issuecomment-1067186975 about the "relative path" that should apply here. Thanks!

**Comment by swinslow** [comment]
Fixed in #114, thank you @CatalinStratu!
