### ISSUE TITLE
 yaml and json are small coverage

### ISSUE THREAD

**Issue by CatalinStratu** [spdx/tools-golang#143]
Hi, I see that yaml and json are small coverage, can I try to add more unit tests for these two packages?

**Comment by ianling** [comment]
Looking at the coverage report, the only lines that are missing coverage are two `if err != nil {` lines. It would be very simple to add tests for those, but all we would be testing is that an error is returned, which it clearly is, so I'm not sure that it adds any value to get coverage there.

If you're bored and feel like doing it, by all means go ahead though.

**Comment by seabass-labrax** [comment]
There is certainly value in getting a 100% coverage report if it reassures future developers that there aren't any gaps :wink:

**Comment by ianling** [comment]
Yeah, just my opinion. I may not be in the majority when I question the meaningfulness of code coverage reports, but if it aids in increasing developer confidence and mass adoption of the SPDX standard, you are absolutely right that there is value there, regardless of whether there is a real effect on code quality.

@CatalinStratu I think you should go ahead and add some tests for these lines that are missing coverage if you'd like. Thanks for your input @seabass-labrax

**Comment by CatalinStratu** [comment]
Hi, @ianling  and @seabass-labrax , I will probably close this issue. Thanks!

**Comment by CatalinStratu** [comment]
Hi, @ianling  and @seabass-labrax , I will probably close this issue. Thanks!
