### ISSUE TITLE
Abstract SPDX versioning

### ISSUE THREAD

**Issue by ivanayov** [spdx/tools-golang#175]
Hi,

Currently most types and methods are named after the SPDX version they parse/represent, which is reasonable for the parser itself, but makes adoption much harder.
It would be great if tools-golang provides some abstraction, so that any tools using it can update the SPDX version via configuration only, rather than doing code updates or refactoring every time, as those are necessary in the parser only.

**Comment by lumjjb** [comment]
HI @ivanayov! Thanks for opening up this issue! Yes, the abstraction need some work and we have an open issue to discuss it (https://github.com/spdx/tools-golang/issues/152)... @kzantow is currently working on the reflection code implementation to provide that abstraction! We'd be happy to get more feedback on how you'd like to use it though!

**Comment by kzantow** [comment]
@ivanayov I've written up a bit of an explanation of the changes I'm hoping to get merged -- do they make sense to you and seem to provide the functionality you're looking for? See the description here: https://github.com/spdx/tools-golang/pull/172#issue-1460418844

**Comment by ivanayov** [comment]
Thank you @lumjjb and @kzantow! I moved the discussion to #172.

Closing as it partially duplicates #152, but I think #172, which is not strictly following the #152 proposal, covers it well and is closer to this issue. I left my comments in the PR.
