### ISSUE TITLE
jsonloader: panic error when parsing creation info

### ISSUE THREAD

**Issue by hectorj2f** [spdx/tools-golang#177]
When using osvscanner, I am facing a panic error in https://github.com/spdx/tools-golang/blob/v0.3.0/jsonloader/parser2v2/parse_creation_info.go#L76.

```
panic: interface conversion: interface {} is map[string]interface {}, not string

goroutine 190 [running]:
github.com/spdx/tools-golang/jsonloader/parser2v2.parseCreators({0x1d476a0?, 0xc000a09b18}, 0xc00001e1c0)
	github.com/spdx/tools-golang@v0.3.0/jsonloader/parser2v2/parse_creation_info.go:76 +0x50c
github.com/spdx/tools-golang/jsonloader/parser2v2.JSONSpdxDocument.parseJsonCreationInfo2_2(0xc001014648?, {0xc000bcb340, 0xc}, {0x1e83260?, 0xc00090c2d0?}, 0xc000ecb200?)
	github.com/spdx/tools-golang@v0.3.0/jsonloader/parser2v2/parse_creation_info.go:50 +0x6ca
github.com/spdx/tools-golang/jsonloader/parser2v2.JSONSpdxDocument.newDocument(0xc000b26800?, 0x586?)
```

**Comment by lumjjb** [comment]
hi @hectorj2f ! by any chance would you be able to share the SPDX file that you are using ?

**Comment by kzantow** [comment]
Also note: this is probably already fixed in the latest main branch -- the custom JSON parser was removed (there were many panics due to lots of custom code) in favor of standard go JSON handling, which probably no longer has this issue. It may be good to try using this library against the `main` branch.

**Comment by kzantow** [comment]
@hectorj2f have you been able to try a more recent release to see if you continue to have this issue?

**Comment by hectorj2f** [comment]
I haven't used it yet. We were using it as part of scorecard, so I was hoping for scorecard to bump their spdx-golang version. I'll try to do it myself.

**Comment by lumjjb** [comment]
Closing this issue for now, please reopen if you still run into any problems @hectorj2f !
