### ISSUE TITLE
tagvalue parser incorrectly complains about DocumentComment

### ISSUE THREAD

**Issue by justinabrahms** [spdx/tools-golang#182]
Hello.

When parsing a tagvalue file, I incorrectly get the error `received unknown tag DocumentComment in CreationInfo section`. I've ensured the file passes validation at https://tools.spdx.org/app/validate/.

File listed here: https://github.com/eBay/sbom-scorecard/issues/22#issuecomment-1381069619

Test case:

```go
package main

import (
	"bytes"
	"fmt"
	"io/ioutil"

	spdx_tv "github.com/spdx/tools-golang/tvloader"
)

func main() {
	f, err := ioutil.ReadFile("/Users/jabrahms/Downloads/photon.spdxtv.txt")
	if err != nil {
		print("error opening SPDX document: %w", err)
		return
	}

	doc22, err := spdx_tv.Load2_2(bytes.NewReader(f))
	if err == nil && doc22 != nil {
		print("Found 2.2 tv document")
	} else {
		fmt.Println("Error: ", err)
	}
}
```

**Comment by neilnaveen** [comment]
@lumjjb  I do not see tvloader package in main. It was their in the release v0.4.0, but now it is gone, how do you want to handle this?

**Comment by justinabrahms** [comment]
@neilnaveen I'm happy if you just fix what's in main.

```go
package main

import (
	"bytes"
	"fmt"
	"io/ioutil"

	spdx_tv "github.com/spdx/tools-golang/tagvalue"
)

func main() {
	f, err := ioutil.ReadFile("/Users/jabrahms/Downloads/photon.spdxtv.txt")
	if err != nil {
		print("error opening SPDX document: %w", err)
		return
	}

	doc22, err := spdx_tv.Read(bytes.NewReader(f))
	if err == nil && doc22 != nil {
		print("Found 2.2 tv document")
	} else {
		fmt.Println("Error: ", err)
	}
}
```

and
```
$ go run main.go
Error:  received unknown tag DocumentComment in CreationInfo section
```

**Comment by neilnaveen** [comment]
Not in your code, but the [main branch](https://github.com/spdx/tools-golang) of spdx.

**Comment by justinabrahms** [comment]
@neilnaveen Totally. I (I think...?) updated the code to reflect the test case with what's in main.

**Comment by lumjjb** [comment]
@justinabrahms does the PR https://github.com/spdx/tools-golang/pull/185 from @neilnaveen fix this for you?

**Comment by lumjjb** [comment]
awesome closing this issue. Thanks @neilnaveen @justinabrahms
