### ISSUE TITLE
Apply fix for reading SPDX tag-value DocumentComment to v2.3

### ISSUE THREAD

**Issue by kzantow** [spdx/tools-golang#186]
The changes from #185 also need to be applied to the `spdx/v2/v2_3` file tree.

cc: @neilnaveen

**Comment by neilnaveen** [comment]
I can work on this, Thanks!

**Comment by kzantow** [comment]
Thanks!

**Comment by neilnaveen** [comment]
Fixed in #187

**Comment by lumjjb** [comment]
@kzantow this seems like we can close this yea?

**Comment by kzantow** [comment]
Yes sir, @lumjjb
