### ISSUE TITLE
Some optional fields are output in JSON even though they are optional

### ISSUE THREAD

**Issue by lumjjb** [spdx/tools-golang#207]
Through checking the output we noticed that a couple of fields were being output even though they are optional

- For example, the Package copyrightText field
- CreationInfo LicenseList field
- A few others that may need checking as well: 
  - licenseConcluded, 
  - licenseDeclared, 
  - licenseInfoFromFiles,
  - packageVerificationCode

Reported on behalf on Google internal user (Amit).

**Comment by kzantow** [comment]
@lumjjb could you be more specific for the version(s) this affects? Some of these fields may have been made optional in 2.3, for example.

**Comment by lumjjb** [comment]
did some investigation
- Package copyrightText field (optional in - PR includes change)
- LicenseListFIeld field (optional starting in 2.3 - PR includes change)
- licenseConcluded, licenseDeclared, licenseInfoFromFiles implementation is correct, there was a change for them to no longer be required
- packageVerificationCode, looks like this is the same for 2.2 and 2.1 as it is for 2.3, 2.1 and 2.2 need to be updated (PR includes change)


TBD: add my in flight PR

**Comment by lumjjb** [comment]
FIxed by #215
