### ISSUE TITLE
Should be able to read and write JSON files

### ISSUE THREAD

**Issue by swinslow** [spdx/tools-golang#23]
SPDX 2.2 will include a new JSON format: see https://github.com/spdx/spdx-spec/blob/development/v2.2/examples/SPDXJSONExample-v2.2.spdx.json

tools-golang should support reading from and writing to SPDX documents in JSON format. This will probably require a translation between the tools-golang data model and an intermediate model for the JSON format.

**Comment by RishabhBhatnagar** [comment]
> SPDX 2.2 will include a new JSON format: see https://github.com/spdx/spdx-spec/blob/development/v2.2/examples/SPDXJSONExample-v2.0.spdx.json

The provided link is broken. The correct link might be https://github.com/spdx/spdx-spec/blob/development/v2.2/examples/SPDXJSONExample-v2.2.spdx.json .

**Comment by swinslow** [comment]
updated the issue, thanks @RishabhBhatnagar!

**Comment by FotiadisM** [comment]
Would it be a good idea to use JSON struct tags to read and write files?

**Comment by RishabhBhatnagar** [comment]
@FotiadisM, definitely. That's exactly how I think this issue should be solved.
That way, we'll be free from the hassles of creating a custom parser, reader, writer, etc without writing much code.

**Comment by swinslow** [comment]
@FotiadisM If you'd like to take a shot at this one, please feel free!

Keep in mind that the canonical JSON file at https://github.com/spdx/spdx-spec/blob/development/v2.2/examples/SPDXJSONExample-v2.2.spdx.json is the format that the JSON files should be in. This may not necessarily reflect the same data structure that is currently used by the SPDX Golang tools -- since the [Golang tools' in-memory data structure](https://github.com/spdx/tools-golang/tree/master/spdx) is different from the [official SPDX data model](https://spdx.github.io/spdx-spec/appendix-III-RDF-data-model-implementation-and-identifier-syntax/). This may make it more complicated to translate to and from JSON than just using JSON struct tags.

**Comment by specter25** [comment]
@swinslow , @RishabhBhatnagar i wanted to contribute in this issue . I have gone through the tvloader code and understood it's working , i hope it will help to fix this issue  . For JSON we don't need a custom parser , we can use struct tags and Golang JSON libraries . Can I take a shot at it ?

**Comment by RishabhBhatnagar** [comment]
@specter25 if you want you may give it a whirl.
If you're interested, this is included as one of the projects for the upcoming gsoc programme.
[https://wiki.spdx.org/view/GSOC/GSOC_ProjectIdeas#JSON_Support_for_Golang_libraries](https://wiki.spdx.org/view/GSOC/GSOC_ProjectIdeas#JSON_Support_for_Golang_libraries).

You can read more about the spdx document specification from the following website: https://spdx.dev/specifications/ .
Feel free to reach out in case of any doubts.

**Comment by specter25** [comment]
Yeah i am interested to work on this issue in GSOC 2021  . I will definitely give it a try. Thanks.

**Comment by varbhat** [comment]
@RishabhBhatnagar @swinslow  
i am also interested in working on this. 


1) There are alternative json parsers too, Should we consider them. 

https://github.com/buger/jsonparser

https://github.com/tidwall/gjson

Latter one feels good too. Can we use them since it may ease some of our work?

2) If we are using struct tags to parse json(which i think that we shouldn't as we can some other method to directly map json to golang's SPDX data model),  is it ok to have converter function to convert from spdx json's data model to default Golang's spdx data model ?

I will work on this at end of this month as exams are underway now. I  want to work on this in GSOC 2021 if i get opportunity. Thanks

**Comment by swinslow** [comment]
Reading JSON files has now been merged as of #87.

**Comment by kzantow** [comment]
Hi, I'm looking at using the JSON reader functionality but hit a snag already: it doesn't work with the examples provided in the spdx-examples repo here: https://github.com/spdx/spdx-examples/tree/master/example7/spdx would you prefer new issues be added or potentially add comments to this one? And would you be amenable to PRs for this? Thanks much!

**Comment by swinslow** [comment]
Hi @kzantow, thanks for this (and apologies for the slow response!)

If the problems you're seeing appear to be with the Golang tools, feel free to file them here. Probably best to file them as new issues so they can be separately tracked, rather than incorporating them into this one. Thank you!

**Comment by swinslow** [comment]
Now that [`jsonsaver`](https://github.com/spdx/tools-golang/tree/main/jsonsaver) has landed in the main branch, I'm going to go ahead and call this resolved. Thank you again @specter25 for all your hard work on implementing the SPDX JSON functionality!
