### ISSUE TITLE
Consider changing data model to IDs as keys

### ISSUE THREAD

**Issue by swinslow** [spdx/tools-golang#24]
Currently, the data model for spdx/tools-golang stores everything in slices. For example:

- [Document2_1](https://github.com/spdx/tools-golang/blob/b68821f66a8d47c441e3da9ab059205e7e30b3f4/spdx/document.go#L8) contains slices of packages, other license sections, relationships, etc.
- [Package2_1](https://github.com/spdx/tools-golang/blob/b68821f66a8d47c441e3da9ab059205e7e30b3f4/spdx/package.go#L118) contains a slice of Files

Although this makes it easy to maintain the ordering of the applicable elements, it also makes lookup extremely difficult. Finding an element with a particular SPDX ID requires walking through the entire slice.

A better method might be for the internal data representation to store SPDX elements in maps, where the SPDXID (or LicenseRef ID) is the key.

If ordering is important to maintain, then an "order" field could also be maintained when reading.

**Comment by swinslow** [comment]
One complication is that this means that you can't add a package to a Document's `Packages` map, unless and until you've got an SPDXID for it. Similar for `Files` and `Snippets`.

That complicates parsing a bit, because it means we can't add it until we've seen an ID... but it doesn't complicate it much, because we're already holding a pointer to the current Package, within the parser itself. So we could just add it to the map either (1) when we first see the SPDXID tag, or (2) when we are moving on to the next Package / File / whatever.

I'm kind of inclined to add it as soon as we see the SPDXID tag, and then to make it an error if there is subsequently a second SPDXID tag for the same item.

**Comment by swinslow** [comment]
There's a related question of whether SPDXID should still be a property of the `Package` / `File` / `Snippet` struct itself. Or whether the key in the relevant map should be the single source of truth for what its identifier is.

I think it should still be a separate element of the individual item, primarily so that you can know what its identifier is just based on the struct itself -- without having to figure out what key was pointing to it in the parent map.

The downside is that it's possible for someone to create an inconsistency by changing the SPDXID, after it has been added to the parent map, but not change the key. This can be mitigated by providing helper functions to change IDs which would change both the key and the ID in the struct at the same time.

**Comment by swinslow** [comment]
...except note also that this highlights that treating unpackaged files as a pseudo-"Package" inside the `Packages` map doesn't really work. Because we can't map an SPDX identifier to the pseudo-Package (since none exists).

This means that probably this should just be replaced with a top-level "UnpackagedFiles" map of ElementIDs to Files at the Document level, and pull it out of the "Packages" map altogether.

**Comment by swinslow** [comment]
Note that for tag-value files, each Snippet section is required to begin with a Snippet SPDX Identifier. From https://spdx.github.io/spdx-spec/5-snippet-information/:

> The first field to start off the description of a Snippet must be the Snippet Identifier in tag:value format.

This means that at least for snippets, we can ensure that as soon as we see one, we can add it to the current Snippets list -- since it will always have an SPDX identifier which we will see first.

**Comment by goneall** [comment]
A few thoughts based on the java tool's redesign from a non-Go programmer.

> A better method might be for the internal data representation to store SPDX elements in maps, where the SPDXID (or LicenseRef ID) is the key.

Agree with this approach.  Having a map or some mechanism to look up based on ID is very convenient.  It is also helpful to have a mechanism to generate a unique ID for document creation use cases.

> One complication is that this means that you can't add a package to a Document's Packages map, unless and until you've got an SPDXID for it. Similar for Files and Snippets.

> I'm kind of inclined to add it as soon as we see the SPDXID tag, and then to make it an error if there is subsequently a second SPDXID tag for the same item.

This is the approach taken in the Java tools and it hasn't caused any issues.  One problem we did run into was having references to SPDX elements before they were created (e.g. within a relationship).  For that, we just maintained a cache of the elements we could not create and add them when parsing was complete and all the elements were added.  If there was a missing element, it would generate an error.

> There's a related question of whether SPDXID should still be a property of the Package / File / Snippet struct itself. 

I would recommenced keeping this as a property.  The Java library overrides the setter to make sure the map and elements stays in sync.

> This means that probably this should just be replaced with a top-level "UnpackagedFiles" map of ElementIDs to Files at the Document level, and pull it out of the "Packages" map altogether.

For the Java code, there is simply a map of all SpdxElements within a document which includes both packages and files (since they subclass elements).  There is a separate property for the Package that references the files.

**Comment by swinslow** [comment]
Thanks @goneall! This is all very helpful. Appreciate your weighing in on the golang tools, it's helpful to get input from folks outside of just my own head  =)

I'm working on a rewrite of the 2.1 golang tools to align with this. Planning to get it changed over to store and permit lookup by ID before I start cloning relevant bits of the code to work with 2.2, so that I'm not later trying to refactor it all at once for multiple versions of the spec.

The additional top-level map of SpdxElements in a document is interesting. In particular I could see it making sense as an easy way to find a file without having to crawl through each Package's set of files one-by-one. I may not implement this right now but I'm going to create a separate issue to consider whether this should be added.
