### ISSUE TITLE
`spdxVersion` incorrectly reported as 2.3 when SBOM specifies 2.2

### ISSUE THREAD

**Issue by viveksahu26** [spdx/tools-golang#248]
There seems to be an issue in the `tools-golang` library where the `spdxVersion` is incorrectly reported. Even when an SBOM with `spdxVersion` set to `2.2` is provided, the library returns `spdxVersion` as `2.3` in the output.

## Steps to Reproduce it ?
- Create an SPDX SBOM file with spdxVersion explicitly set to 2.2.
- Use the tools-golang library to parse or load the SBOM.
- Observe that the output contains spdxVersion: 2.3 instead of 2.2.

To make it simple, I have reproduce this for you in a separate repository: https://github.com/viveksahu26/golang-tools

## Expected Behavior:
- The `spdxVersion` in the output should match the version specified in the input SBOM file, in this case, 2.2.

## Actual Behavior:
- The spdxVersion in the output is 2.3, even though the input specifies 2.2.

## Impact 
[sbomqs](https://github.com/interlynk-io/sbomqs/) is a quality assessment and compliance checking tool that scores your SBOM based on various fields. An incorrect `spdxVersion` directly impacts the score for this specific field.

Related issue: https://github.com/interlynk-io/sbomqs/issues/349

**Comment by kzantow** [comment]
Hi @viveksahu26 -- the library both parses older versions, such as 2.1 tag-value and 2.2 JSON and converts these to the "current" version, of 2.3 (and eventually, 3.0, when support is implemented). The reason for this is that [2.1, 2.2, and 2.3 are all separate data models](https://github.com/spdx/tools-golang/tree/main/spdx/v2), so if you are going to treat these differently, you will have to have multiple duplicate branches of your code operating on each independent data model. By converting all documents to the same version, it allows you to write code dealing with all versions more generically. If you want to get different versions of the SPDX you can always [convert the document](https://github.com/spdx/tools-golang/blob/main/json/reader.go#L82), or simply start with the specific versions you want and [check which one you should be using, just as the JSON decoder does](https://github.com/spdx/tools-golang/blob/main/json/reader.go#L51-L80).
