### ISSUE TITLE
Should warn or error for pkgs / files without SPDX IDs

### ISSUE THREAD

**Issue by swinslow** [spdx/tools-golang#26]
Placeholder for now, to handle after #24 is implemented:

Should be sure that tvparser either warns or errors out upon seeing a Package or File section that is incomplete due to lack of an SPDX ID.

For example, a new package section will be started when the next `PackageName` tag is seen, but if it goes on to the next Package or File without seeing an `SPDXID` tag for that first Package, then it will not be added to the Packages map for that document. The same applies for Files (but not relevant for Snippets, see https://github.com/spdx/tools-golang/issues/24#issuecomment-626216095)

Lack of an SPDX ID makes the document invalid, but consider whether the parser should treat it as an error, a warning, and/or configurable for either of those or to optionally ignore.

**Comment by specter25** [comment]
@swinslow sir , i want to work on this . Can i start ?
