### ISSUE TITLE
Failing Tests on Windows Machine

### ISSUE THREAD

**Issue by RishabhBhatnagar** [spdx/tools-golang#30]
I am on a Windows 10 Home Version 1909 OS,
The tests are failing on my machine. 

The following command was used to test all the packages recursively.
`go test ./...` was run in the root directory.

[This link](https://pastebin.com/raw/Gm4xZKW1) has the output of the test.

**Comment by swinslow** [comment]
Thanks @RishabhBhatnagar! I'll take a look.

**Comment by RishabhBhatnagar** [comment]
Upon retrying to test using golang version 1.18beta2, 
The tests ran successfully. 

Closing now as the issue not reproducible anymore.
If anyone faces this error in the future, feel free to re-open the issue.

**Comment by swinslow** [comment]
Thank you @RishabhBhatnagar! Appreciate you having checked back on this one  :)
