### ISSUE TITLE
Fix multiline snippet copyright in tvsaver

### ISSUE THREAD

**Issue by swinslow** [spdx/tools-golang#31]
Currently, in tvsaver, Snippet copyright text lines are not saved with a `textify` call: https://github.com/spdx/tools-golang/blob/feb87345dfd6d6f76a9b1fc2ef413a2e8a756be8/tvsaver/saver2v1/save_snippet.go#L36

(compare, for Files, https://github.com/spdx/tools-golang/blob/feb87345dfd6d6f76a9b1fc2ef413a2e8a756be8/tvsaver/saver2v1/save_file.go#L42 and corresponding test at https://github.com/spdx/tools-golang/blob/feb87345dfd6d6f76a9b1fc2ef413a2e8a756be8/tvsaver/saver2v1/save_file_test.go#L213)

A `textify` call should likely be added in tvsaver for both 2.1 and 2.2, after confirming that the spec Snippet copyright lines should wrap if multi-lined.

**Comment by bisakhmondal** [comment]
Hello @swinslow, I'd like to open a PR with the fix. Would you mind if I do it? Currently, there is no test for multiline `SnippetCopyrightText`, should I add one too?
Thanks.

**Comment by swinslow** [comment]
Thanks @bisakhmondal, yes, please feel free to submit a PR! And yes, grateful if you can include a test so that it checks for this case.

**Comment by bisakhmondal** [comment]
Submitted :). I'd appreciate your feedback. Thank you.

**Comment by djfemz** [comment]
Hi @swinslow , is this issue still open? I would like to try my hand out on this.
