### ISSUE TITLE
Handle additional checksums permitted by 2.2

### ISSUE THREAD

**Issue by swinslow** [spdx/tools-golang#41]
In SPDX 2.1 and earlier, the only hash algorithms that were permitted for e.g. File checksums, Package checksums, etc. were SHA1 (mandatory), SHA256 (optional) and MD5 (optional). Because of this, those fields were represented as three separate fields, one for each checksum type (see e.g. [here](https://github.com/spdx/tools-golang/blob/5a270f97f4106cf989761f9143e23132c1bffb3c/spdx/file.go#L20)).

In SPDX 2.2, several additional algorithms were permitted to be used (see [section 4.4 of the spec](https://spdx.github.io/spdx-spec/4-file-information/#44-file-checksum)). The tools-golang model doesn't currently allow these to be used.

Rather than adding more optional fields for each algorithm, I'm more inclined to switch to something where there is a `Checksum` type defined, with something like the following:

```go
type Checksum2_2 struct {
    Type ChecksumType
    Value string
}
```

and then using a series of consts / enums to represent the different algorithms:

```go
// should this all be ChecksumType2_2, etc. instead of just ChecksumType?
type ChecksumType int

const (
    CHECKSUM_TYPE_SHA1 = iota
    CHECKSUM_TYPE_SHA256
    // . . .
)
```

and then changing the various Checksum fields in Package, File, etc. to be a slice of `Checksum2_2`.

@RishabhBhatnagar I'd be interested in your thoughts on this approach!

**Comment by RishabhBhatnagar** [comment]
Having merged #60, we can close this issue.
