### ISSUE TITLE
[Optional Upgrade] Remove Duplicate Prefixes In The Field Names

### ISSUE THREAD

**Issue by RishabhBhatnagar** [spdx/tools-golang#47]
Some of the structs in the tools-golang spdx data model has members that repeat the name of the struct in their name.
The member of such structs should be refactored to remove the name of the struct they are contained in.

For example, 
[Package struct](https://github.com/spdx/tools-golang/blob/4ca6cd1fc37977db1969fcfdfa33dabbb2588010/spdx/package.go#L6) have fields like PackageName, PackageVersion, etc. 
Fields of Package struct can be renamed to Name, Version, etc.

**Comment by swinslow** [comment]
+1, this is a good idea. The struct fields have the names they currently do because I was closely mirroring the tag-value field names. But it would be shorter and simpler to use without having to repeat the prefix over and over.

**Comment by epicadk** [comment]
Hey , Can I work on this?

**Comment by swinslow** [comment]
Hi @epicadk, certainly, you're welcome to try this out if you would like!

Note that in addition to renaming the members within the various structs in the [spdx package](https://github.com/spdx/tools-golang/tree/master/spdx), you'll then need to also make conforming changes to [the other packages in the golang tools](https://github.com/spdx/tools-golang) that use those structs.

Feel free to ask me or @RishabhBhatnagar if you have any questions. @RishabhBhatnagar, feel free to weigh in also if you have thoughts here (or if you've already started on this).

**Comment by epicadk** [comment]
> Hi @epicadk, certainly, you're welcome to try this out if you would like!
> 
> Note that in addition to renaming the members within the various structs in the [spdx package](https://github.com/spdx/tools-golang/tree/master/spdx), you'll then need to also make conforming changes to [the other packages in the golang tools](https://github.com/spdx/tools-golang) that use those structs.
> 
> Feel free to ask me or @RishabhBhatnagar if you have any questions. @RishabhBhatnagar, feel free to weigh in also if you have thoughts here (or if you've already started on this).

Will I also have to change their occurrences in strings? For example in parse_package.go 

`switch tag {
	case "PackageName":......` 
Should I also edit this string?

**Comment by RishabhBhatnagar** [comment]
@epicadk, thanks for taking this issue.
If you haven't seen it already, you can refer to the [UML](https://github.com/spdx/spdx-spec/blob/development/v2.2.1/model/SPDX-UML-Class-Diagram.jpg) and [spdx-spec](https://spdx.github.io/spdx-spec/) for more details on the naming. It would be better if the data model stays as close to the documentation as possible.

**Comment by swinslow** [comment]
As mentioned at https://github.com/spdx/tools-golang/pull/57#issuecomment-873595921, I'm going to close this issue for now, as the existing field names are getting used by users of the project. As the tools-golang community grows, we can re-evaluate and reconsider in the future if appropriate.
