### ISSUE TITLE
tvsaver: check multiline <text> tag wrapping

### ISSUE THREAD

**Issue by swinslow** [spdx/tools-golang#53]
From some recent testing on saving tag-value documents, it looks like some multiline fields are not getting correctly wrapped with `<text>...</text>` tags when they run over more than a single line.

In particular, I've noticed it for the following fields, when reading from an RDF file (the [canonical RDF sample file](https://github.com/spdx/spdx-spec/blob/development/v2.2.1/examples/SPDXRdfExample-v2.2.spdx.rdf.xml#L990)) and saving out as a 2.2 tag-value file:
* FileComment
* FileNotice
* LicenseComment

**Comment by specter25** [comment]
@swinslow this can be fixed if the wrap the above mentioned fields inside the textify function  when they are being written to the io.Writer i believe .

**Comment by specter25** [comment]
@swinslow can i work on this issue.

**Comment by shubhamgupta2956** [comment]
Hello everyone, I would like to work on this issue. Can I start?

**Comment by swinslow** [comment]
Closing, addressed in #76
