### ISSUE TITLE
jsonloader: "excludes" in packageVerificationCode

### ISSUE THREAD

**Issue by swinslow** [spdx/tools-golang#79]
cc @specter25 

In the `json` branch, when parsing the `packageVerificationCode` object, it appears that the current JSON parser is expecting an `excludes:` tag to be present within the array elements:

https://github.com/spdx/tools-golang/blob/8a86c1f72d8c1181841b3e4ee66c424862dba357/examples/8-jsonpasrser2v2/test.json#L99-L102

For parsing tag-value documents, that would be correct: the tag-value spec requires `excludes:` to be present.

However, looking at the sample JSON file from the SPDX spec, `excludes:` is not present and the array element is just the filename itself:

https://github.com/spdx/spdx-spec/blob/3dddfc34d7e770d4c17fc19f61be8554e3934c3d/examples/SPDXJSONExample-v2.2.spdx.json#L100-L103

Also, when running some tests using the [SPDX Online Tools converter](https://tools.spdx.org/app/convert/), it appears to me that the version from the spec samples is also used there; `excludes:` is not present.

So, I believe that when parsing that field, you won't want to look for an `excludes:` tag in the array element, and instead you'll want to just take the array element directly as the filename.

**Comment by specter25** [comment]
cc @swinslow 

https://github.com/spdx/spdx-spec/blob/master/examples/SPDXJSONExample-v2.2.spdx.json#L100-L103

The JSON example file in the master branch of that repository has the excludes: tag before the file name . So should I still remove it , or add compatibility for both the situations whether the excludes tag is present or not .

**Comment by swinslow** [comment]
Hmm... good point. The primary and default branch for the spdx-spec repo is development/v2.2.1, and the JSON example there is the one that's continuing to be updated.

That said, if it's straightforward to handle either case -- check for "excludes" if it's there, and handle either case -- that would be ideal. Thanks!

**Comment by swinslow** [comment]
Appears to be fixed in #83, thanks @specter25!
