### ISSUE TITLE
Tvsaver : invalid tag SnippetSPDXIdentifier 

### ISSUE THREAD

**Issue by specter25** [spdx/tools-golang#93]
cc @swinslow 

The tag-value saver has a parses Snippet SPDX Id's incorrectly using the tag SnippetSPDXIdentifier whereas it should be SnippetSPDXID as defined in the SPDX specification .

**Comment by swinslow** [comment]
Great catch, thanks @specter25! I'll take a look at this and will fix it.

**Comment by swinslow** [comment]
Fixed with #95, thank you @specter25!
